<?php
session_start();

$servername = "localhost";
$username = "root";
$password = "";
$dbname = "fk_scems_db";

$conn = new mysqli($servername, $username, $password, $dbname);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // 1. Collect data from HTML form
    $name     = $_POST['name'];         // To be stored in 'admin' table
    $user     = $_POST['username'];     // To be stored in 'user' table
    $email    = $_POST['email'];        // To be stored in 'user' table
    
    // SECURE HASHING APPLIED HERE
    $plain_pass = $_POST['password'];     
    $hashed_pass = password_hash($plain_pass, PASSWORD_DEFAULT);
    
    $contact  = $_POST['contact_no'];   // To be stored in 'user' table
    $role     = "Admin";                // Default role

    // 2. Start Transaction
    $conn->begin_transaction();

    try {
        // Step A: Insert into 'user' table (Binding $hashed_pass instead of $plain_pass)
        $sql_user = "INSERT INTO user (username, email, password, role, contact_no) VALUES (?, ?, ?, ?, ?)";
        $stmt_user = $conn->prepare($sql_user);
        $stmt_user->bind_param("sssss", $user, $email, $hashed_pass, $role, $contact);
        $stmt_user->execute();

        // Get the new user_id generated by the 'user' table
        $new_user_id = $conn->insert_id;

        // Step B: Insert into 'admin' table
        // staff_id is omitted here because it is AUTO_INCREMENT
        $sql_admin = "INSERT INTO admin (user_id, name) VALUES (?, ?)";
        $stmt_admin = $conn->prepare($sql_admin);
        $stmt_admin->bind_param("is", $new_user_id, $name);
        $stmt_admin->execute();

        // Commit both inserts
        $conn->commit();

        echo "<script>
                alert('Admin Registered Successfully! Your Staff ID has been generated automatically.');
                window.location.href = 'login.php';
              </script>";
        exit();

    } catch (Exception $e) {
        // Rollback if username/email is duplicate or any error occurs
        $conn->rollback();
        
        echo "<script>
                alert('Error: Registration failed. The username or email might already be taken.');
                window.history.back();
              </script>";
    }
}

$conn->close();
?>